<?php

namespace App\Infrastructure\Persistence;

use App\Domain\User\Repositories\UserRepositoryInterface;  // Interface that defines the user repository methods
use App\Domain\User\Entities\User as DomainUser;            // Domain model for user entity
use App\Models\User as EloquentUser;                         // Eloquent model that interacts with the database

// EloquentUserRepository implements the UserRepositoryInterface.
// It provides the functionality to interact with the database using the Eloquent ORM to perform CRUD operations.
class EloquentUserRepository implements UserRepositoryInterface
{
    /**
     * Save a user.
     *
     * This method takes a DomainUser object, creates a corresponding EloquentUser model instance, 
     * and saves it in the database. It then returns the saved DomainUser with the generated ID.
     *
     * @param DomainUser $domainUser
     * @return DomainUser
     */
    public function save(DomainUser $domainUser): DomainUser
    {
        // If the ID is null (new user), create the user in the Eloquent model
        $model = EloquentUser::create([
            'name' => $domainUser->name,    // Set the 'name' attribute of the user
            'email' => $domainUser->email,  // Set the 'email' attribute of the user
            'password' => bcrypt($domainUser->password),  // Hash the 'password' before saving
        ]);

        // Return the DomainUser object with the ID (auto-generated by the database)
        return new DomainUser(
            $model->id,         // Set the ID generated by the database
            $model->name,       // Set the name from the saved model
            $model->email,      // Set the email from the saved model
            $model->password    // Set the hashed password from the saved model
        );
    }

    /**
     * Retrieve all users.
     *
     * This method fetches all users from the database and maps them to DomainUser objects.
     *
     * @return array
     */
    public function getAll(): array
    {
        // Fetch all EloquentUser models from the database and map each to a DomainUser
        return EloquentUser::all()->map(function ($model) {
            // Convert each EloquentUser model to a DomainUser instance
            return new DomainUser($model->id, $model->name, $model->email, $model->password);
        })->all();  // Return all DomainUser objects as an array
    }

    /**
     * Find a user by ID.
     *
     * This method finds a user in the database by their ID. If the user is not found, 
     * it will throw a `ModelNotFoundException` by default (because of `findOrFail`).
     *
     * @param int $id
     * @return DomainUser
     */
    public function findById(int $id): DomainUser
    {
        // Fetch user by ID. If not found, it will throw an exception.
        $model = EloquentUser::findOrFail($id);  // 'findOrFail' will throw an exception if the user is not found

        // Return a DomainUser object with the retrieved data
        return new DomainUser($model->id, $model->name, $model->email, $model->password);
    }

    /**
     * Update an existing user's details.
     *
     * This method updates an existing user's details in the database, 
     * including the name, email, and password (if provided).
     *
     * @param DomainUser $domainUser
     * @return DomainUser
     */
    public function update(DomainUser $domainUser): DomainUser
    {
        // Find the existing Eloquent model by the user's ID
        $model = EloquentUser::findOrFail($domainUser->getId());  // 'findOrFail' retrieves the user or throws an error if not found

        // Update the model with new values from the DomainUser
        $model->name = $domainUser->getName();   // Update the 'name' attribute
        $model->email = $domainUser->getEmail(); // Update the 'email' attribute

        // If the DomainUser has a new password, hash it and update the model
        if ($domainUser->getPassword()) {
            $model->password = bcrypt($domainUser->getPassword());  // Hash the new password before saving
        }

        // Save the updated model in the database
        $model->save();

        // Return the updated DomainUser object
        return new DomainUser($model->id, $model->name, $model->email, $model->password);
    }
}
